node {
   stage('Compile') {
	  git url: 'https://github.com/olivierderuelle/testRepo1'
      def mvn_version = 'M3'
	  def javaHome = tool 'JAVA_HOME'
      withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
	    bat "JAVA_HOME=$javaHome mvn -f test1/pom.xml clean compile"
	  }
   }
   stage('Test') {
      def mvn_version = 'M3'
      withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
	    bat "mvn -f test1/pom.xml test"
	  }
   }
   stage('Build') {
      def mvn_version = 'M3'
      withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
	    bat "mvn -f test1/pom.xml package docker:build"
	  }
   }
}