node {
   stage('Build1') {
	  git url: 'https://github.com/olivierderuelle/testRepo1'
      def mvn_version = 'M3'
      withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
	    sh "mvn -f test1/pom.xml clean install"
	  }
   }
}